# Generated by Django 3.1.7 on 2021-03-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20210307_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='description',
            new_name='descricao',
        ),
    ]
